### ISSUE TITLE
Tooltip error

### ISSUE THREAD

**Issue by Cazzbr** [LanceDH/WorldQuestTab#1]
![wowscrnshot_090717_194256](https://user-images.githubusercontent.com/31737100/30188471-e5fd9424-9404-11e7-91ba-0877abe95bb6.jpg)

when I open the World map with the World quests tab open, this tooltip appears. As far I could track Its related to the item comparison feature cuz It's only shows after I mouse over a world quest on the list the awards an item.
I appears on every map updated, when I switch zones or open the map, desappears when I mouse over element.

**Comment by LanceDH** [comment]
Looks like this happens when you have the alwaysCompareItems CVar set to 1.
I found the culprit and a way to fix it.
However, as the CVar isn't available in the official settings of the game, I see it as a minor issue.
This means I'll wait with releasing an update with the fix to either combine it with other issues, or I'll push it somewhere next week. Simply to not shower people with updates.

If, however, you know your way around addons and would like to have this issue fixed now, you can do the following:
In the addon folder open WorldQuestTab.xml
On line 746 you will find
```xml
<GameTooltip name="WQT_Tooltip" frameStrata="TOOLTIP" hidden="true" parent="WorldMapFrame" inherits="GameTooltipTemplate">
```
replace this with
```xml
<GameTooltip name="WQT_CompareTooltip1" clampedToScreen="true" frameStrata="TOOLTIP" hidden="true" parent="WorldMapFrame" inherits="ShoppingTooltipTemplate"/>
<GameTooltip name="WQT_CompareTooltip2" clampedToScreen="true" frameStrata="TOOLTIP" hidden="true" parent="WorldMapFrame" inherits="ShoppingTooltipTemplate"/>
<GameTooltip name="WQT_Tooltip" frameStrata="TOOLTIP" hidden="true" parent="WorldMapFrame" inherits="GameTooltipTemplate">
```
And on line 760 (after the previous change), replace
```xml
self.Tooltip.shoppingTooltips = { WorldMapCompareTooltip1, WorldMapCompareTooltip2 };
```
with
```xml
self.Tooltip.shoppingTooltips = { WQT_CompareTooltip1, WQT_CompareTooltip2 };
```
Then simply save the file, reload your UI, and the issue should be fixed.

**Comment by Cazzbr** [comment]
Thank you, this fixed the issue.
